### ISSUE TITLE
Implement recommended community standards to the project

### ISSUE THREAD

**Issue by orama254** [colbyfayock/next-cloudinary#10]
Hello @colbyfayock 

I was going though this project and noticed that there are some missing items based on the [Github Community Standards recommendations](https://github.com/colbyfayock/next-cloudinary/community) that would make the project contributor friendly, e.g. a Licence, an issue template and a pull request template.

Let me know if this is something you would like to implement.

**Comment by colbyfayock** [comment]
thanks @orama254 that would be great, if you could finish that list, I would appreciate it and we can get that merged in

i haven't done any of the templates for GitHub projects before so let me know if there are any questions i can answer as you're working throug hthem

as far as license, please use MIT. thanks

**Comment by orama254** [comment]
awesome @colbyfayock 

I'll be sending a pull request shortly with some suggestions you can review.
