### ISSUE TITLE
[Bug] CldImage does not support Next Image fill

### ISSUE THREAD

**Issue by esguerrat** [colbyfayock/next-cloudinary#110]
# **Bug Report**

## **Describe the bug**

I am trying to move from NextJS's next/image over to your CldImage so I can fetch images directly from Cloudinary but when I try to swap my tag I get this error header sent back at runtime: `x-cld-error: Invalid width in transformation: NaN`. It seems that NextImage can accept fill={true} and not need a width or height specified but CldImage cannot. 

This is unexpected because the documentation states 'At its core, Next Cloudinary offers a [CldImage](https://next-cloudinary.spacejelly.dev/components/cldimage/basic-usage) component that wraps and extends the [Next.js Image](https://nextjs.org/docs/api-reference/next/image) component, giving you the same developer experience you expect from Next.js, while providing the features and performance you love from Cloudinary."

## **Expected behaviour**

I expected that it would offer the same functionality as the underlying component.

**Comment by Max29a** [comment]
That's my issue thanks. Let me know if there is any more info I can provide

**Comment by colbyfayock** [comment]
i went ahead and merged it in since it fixes the bug. let me know if i seem to be missing anything though!

**Comment by Max29a** [comment]
> hey @Max29a created a PR here: #113
> 
> wanted to confirm the expectation of the feature as it's not a feature I usually use
> 
> If you look at the example I added to test this:
> 
> https://next-cloudinary-keak0yptx-colbyfayock.vercel.app/components/cldimage/examples#next-image-features
> 
> i set a height explicitly on the parent and by default, Next.js fills that container, so the image warps a bit unless you use something like object-fit (per docs)
> 
> is this what you expect? anything missing?

This does sound like what I am expecting thanks. I am using object-fit as referenced here: https://nextjs.org/docs/api-reference/next/image#fill
