### ISSUE TITLE
[Bug] CldUploadWidget throws TypeError when `signatureEndpoint` is present

### ISSUE THREAD

**Issue by fartinson** [colbyfayock/next-cloudinary#124]
Hi, when `signatureEndpoint ` is added to the upload or button upload widget this error appears: `TypeError: widget.current.open is not a function. (In 'widget.current.open()', 'widget.current.open' is undefined)` when clicking the button to open the UI.

**Comment by colbyfayock** [comment]
hey thanks for reporting this. can you show me an example of using it where that occurs?

the docs example isn't trggering that for me in the examples:

https://github.com/colbyfayock/next-cloudinary/blob/main/docs/pages/components/clduploadwidget/examples.mdx?plain=1#L66

the project was recently moved to TypeScript so i suspect that was part of the issue

also make sure you're on the latest version in case the issue has been addressed already

**Comment by colbyfayock** [comment]
hey @fartinson since i haven't heard back, i'm goign to close this issue, but please re-open if you're still seeing it on the latest version

I've also just released an update 2.3.0 that includes Typescript fixes: https://github.com/colbyfayock/next-cloudinary/pull/131
