### ISSUE TITLE
[Feature] Support nextJS Canary builds

### ISSUE THREAD

**Issue by hades200082** [colbyfayock/next-cloudinary#127]
Can you update the dependency config to allow it to work with canary builds?

```
npm ERR! Found: next@13.1.7-canary.10
npm ERR! node_modules/next
npm ERR!   next@"^13.1.7-canary.10" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^12 || ^13" from next-cloudinary@2.2.0
```

**Comment by colbyfayock** [comment]
hey @hades200082 any chance you know how to do this already? i did a quick search and was having trouble finding it, will try to dig into it more, but happy to do it or generally fix how i'm managing the peer dependencies

**Comment by hades200082** [comment]
I'm not sure it's going to be practical tbh. 

https://stackoverflow.com/questions/67934358/npm-including-all-range-of-pre-release-when-defining-peer-dependency

I ended up fixing my problem using overrides as documented in the answer at https://stackoverflow.com/questions/71479750/npm-install-pre-release-versions-for-peer-dependency

**Comment by colbyfayock** [comment]
ah, bummer okay. since you figured out a solution will close, but if others seem to want a solution from the package, can raise it back up. thanks
