### ISSUE TITLE
[Bug] TypeScript: Some props missing from CldImageProps, ie crop, zoom, gravity

### ISSUE THREAD

**Issue by joelmturner** [colbyfayock/next-cloudinary#133]
# **Bug Report**

## **Describe the bug**
It appears that crop, zoom, and gravity are missing from `CldImageProps`, or if this is intentional, the docs have those listed as props.

Since these are untyped, they throw the type error. The props still function correctly - the output has the applied options - if types are ignored.

## **Is this a regression?**

This "worked" before the types were present (since there weren't any types).

## **Steps To Reproduce the error**

1. Create a new CldImage component
2. try to add crop, zoom, or gravity

## **Expected behaviour**

Ideally, these would be part of the CldImageProps so we get type hints and linting.

## **CodeSandbox or Live Example of Bug**

[CodeSandbox Reproduction](https://codesandbox.io/p/sandbox/divine-morning-ykivt0?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A23%2C%22endLineNumber%22%3A13%2C%22startColumn%22%3A23%2C%22startLineNumber%22%3A13%7D%5D)

## **Screenshot or Video Recording**

<img width="980" alt="Screen Shot 2023-02-17 at 5 18 43 PM" src="https://user-images.githubusercontent.com/1114495/219823954-55760d52-33fe-4fd1-be69-d1f3b874bc8b.png">

### **Your environment**

- OS: MacOs 12.4
- Node version: v16.19.0
- Npm version: 9.3.1
- Yarn version: 1.22.18
- Browser name and version: Arc Version 0.90.0 (37254)

## **Additional context**

I can add the types if they are intended to be in the `CldImageProps`.

**Comment by colbyfayock** [comment]
agh thanks - feels like every time i feel like i make progress with TS i end up back a step 😭 will get this addressed!

**Comment by colbyfayock** [comment]
you're welcome to add the types but it's a bigger problem. those wouldn't be the only ones that are throwing errors i assume

the design i went with for supporting a variety of props and effects is a "plugin" treatment where there isn't a simple list of props like that in this package (outside of the docs lol)

this however is defined inside of the abstracted Cloudinary Util: https://github.com/colbyfayock/cloudinary-util/blob/main/packages/url-loader/src/types/image.ts#L10

im hoping to figure out a better solution moving forward, so far ive been recommended to check out Zod, but i think in the short term i need to export `ImageOptions` from Cloudinary Util, and use that for `CldImageProps`

open to feedback / ideas on this

this has been a big learning process for me wrt Typescript as ive been converting the project

**Comment by colbyfayock** [comment]
@joelmturner mind giving a 2nd pair of eyes on this?

https://github.com/colbyfayock/next-cloudinary/pull/134

i exported the types from Cloudinary Util and am now combining it with the Next Image props to create CldImage Props

seems to be working when importing it locally from my filesystem

<img width="1361" alt="image" src="https://user-images.githubusercontent.com/1045274/219829521-b2a9b0b6-53a9-40af-b66b-413e9b06591e.png">

**Comment by joelmturner** [comment]
@colbyfayock That PR looks great! Nice quick solution and turnaround :).

I ran it locally and everything seems to be working. I like the solution here, pulling them in from Cloudinary utils. Hopefully, that can continue to be the source of truth for those option types/definitions.

I haven't messed with Zod yet but I could see it being helpful. So many things to learn, so little time.

**Comment by colbyfayock** [comment]
awesome thanks for looking! 🙌
