### ISSUE TITLE
Add Types for CldUploadWidget options

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-cloudinary#140]
### Discussed in https://github.com/colbyfayock/next-cloudinary/discussions/139

**Comment by colbyfayock** [comment]
@ruben00001 added a bunch here, hows this look? https://github.com/colbyfayock/next-cloudinary/pull/141

**Comment by ruben00001** [comment]
> @ruben00001 added a bunch here, hows this look? #141

Looks great, nice one. There are of course lots more parameters as listed on the [reference page](https://cloudinary.com/documentation/upload_widget_reference#sources_parameters) but it'd be ridiculous to have to type them all out. It's a shame Cloudinary doesn't provide types!

**Comment by colbyfayock** [comment]
I did type them all out 😬😂
