### ISSUE TITLE
[Bug] can't resolve next/head in storybook in nx monorepo

### ISSUE THREAD

**Issue by stijnjanmaat** [colbyfayock/next-cloudinary#153]
# **Bug Report**

## **Describe the bug**

We have a nx monorepo, with storybook in a separate app from the next instance. I have a storybook story about a component using the `CldImage` component, and upon start storybook it throws:
```
ModuleNotFoundError: Module not found: Error: Can't resolve 'next/head' in '/Users/sjanmaat/code/[...]/node_modules/next-cloudinary/dist'
Did you mean 'head.js'?
BREAKING CHANGE: The request 'next/head' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
```

Storybook itself can find `next/head`, I can import it in `preview.jsx` no problem.
The `next-cloudinary` package can be found in the root node_modules, just like `next`.

## **Is this a regression?**

I don't think so. I'm new to this package.

## **Expected behaviour**

I expect it to find next/head.

### **Your environment**

next-cloudinary 3.4.0
Storybook 6.5.16 built with webpack5
nx 14.1.5
yarn 3.3.1

- OS: MacOS Ventura
- Node version: 16
- Npm version: 8.15.0, but we use yarn 3.3.1
- Browser name and version: Chrome

## **Additional context**

I have set up a next instance with create-next-app, with storybook 7 beta and CldImage and then it does work fine.
Next I'll try a clean nx monorepo setup and see if that works.

**Comment by colbyfayock** [comment]
hey @stijnjanmaat do you have a public repo available i could spin up and poke at?

i haven't used nx before and haven't tried adding any of the components to storybook yet

**Comment by stijnjanmaat** [comment]
In the mean time, I have found a workaround for the error for Storybook 6.5 by adding this to `webpackFinal` in `.storybook/main.js`:
```js
  webpackFinal: async (config) => {
    const newConfig = config;

    newConfig.resolve.alias = {
      ...newConfig.resolve.alias,
      'next/head': false,
      'next/script': false,
    };

    [...]

    return newConfig;
  },
```

Then i ran into the next error: `Uncaught You must supply a cloudName when initializing the asset`
But that was fixed by setting `NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME="my-cloud-name"` in .env of storybook.

So in short, now have a working CldImage in Storybook albeit with a workaround.

**Comment by colbyfayock** [comment]
awesome 🎉 

do you think this ultimately is a Next Cloudinary related issue? mostly wondering if there's anything i can do to help address this as opposed to it somehow being an issue between storybook and Next (especially given 7 beta works)

**Comment by stijnjanmaat** [comment]
I don't really know to be honest... but i'm okay with this work around until Storybook 7 is released, which should be very soon, March 14 2023: https://www.thedroptimes.com/27692/storybook-will-hit-version-70-march#:~:text=Those%20who%20are%20familiar%20with,about%20to%20hit%20version%207.0.

**Comment by colbyfayock** [comment]
Ah soon then. Okay. Gonna close for now. Thanks for looking into this and the info
