### ISSUE TITLE
[Feature] On Load Callback

### ISSUE THREAD

**Issue by jamesqquick** [colbyfayock/next-cloudinary#155]
# **Feature Request**
I'd like to know when the image has finally been loaded.

I'm building a meme generator where I will dynamically update the overlay text to then re-render the new image. During the re-render process I'd like to show a loading indicator, but right now I have no way of knowing when the image has completely loaded.

## **Describe the solution you'd like**

I'd love to have pass an `onLoaded` prop to the component which will call back to my function when it has been fully loaded.

## **Describe alternatives you've considered**

Just guess...? lol

**Comment by colbyfayock** [comment]
Closing per PR comments as the options can just be passed right into the component.
