### ISSUE TITLE
[Bug] Infinite gray modal loading on staging/prod - working locally

### ISSUE THREAD

**Issue by pixeliner** [colbyfayock/next-cloudinary#162]
# **Bug Report**

## **Describe the bug**

I'm using the CloudinaryUploadButton and have no issues in using it locally. Now I made a build of my NextJs app and put it on Staging (secure url). Whenever I click on the button, I get a gray modal which loads indefinetly. No errors in the console or network tab. 

## **Expected behaviour**

To simply open and work ;)

## **CodeSandbox or Live Example of Bug**

This is my component

```
import { Button } from '@mui/material';
import { CldUploadWidget } from 'next-cloudinary'

interface CloudinaryUploadButtonProps {
  onUpload: (result: any, widget: any) => void;
}

const CloudinaryUploadButton = ({ onUpload }: CloudinaryUploadButtonProps) => {
  return (
    <CldUploadWidget uploadPreset="..." onUpload={onUpload}>
      {({ open }) => {
        function handleOnClick(e: any) {
          e.preventDefault();
          open();
        }
        return (
          <Button onClick={handleOnClick}>
            Upload an Image
          </Button>
        );
      }}
    </CldUploadWidget>
  )
}

export default CloudinaryUploadButton;

```

## **Screenshot or Video Recording**

![Screenshot 2023-03-22 173128](https://user-images.githubusercontent.com/25492845/226973711-fcb93cc2-2f47-41f3-bb9e-edac88558b82.png)

### **Your environment**

- OS: 
- Node version: Dockerimage node:18-alpine
- Browser name and version: Chrome Version 111.0.5563.64
- next-cloudinary: "^4.0.0"

**Comment by pixeliner** [comment]
Okay it seemed there was an underlying issue. The problem is that you need to take the NEXT_PUBLIC_ variables into account when using pipelines as they are only set during build time. As my cloudname was undefined, it got stuck. It would have saved me some time if there was an error message :)

**Comment by colbyfayock** [comment]
Id be happy to add one but could you elaborate a little bit? Is it because it wasn't available in the CI?
