### ISSUE TITLE
[Bug]: Error after yarn start

### ISSUE THREAD

**Issue by Mart1n991** [colbyfayock/next-cloudinary#163]
# **Bug Report**

Hi, I cloned cloudinary from a repo and made `yarn install` After everything was installed I did `yarn start` and this error shows in the console. 

<img width="733" alt="image" src="https://user-images.githubusercontent.com/62892540/227433426-6d79b01b-a437-495c-9283-e97947a5d0ed.png">

I tried also `npm install` but it was still the same. 

## **Steps To Reproduce the error**

1. Run ``` npx degit hygraph/hygraph-examples/uix-cloudinary-input uix-cloudinary-input ``` 
2. Go to project directory
3. Run ``` yarn install ``` or ``` npm install ```
4. Run ``` yarn start ``` or ``` npm start ```

### **My environment**

- OS: Mac OS Ventura 13.2.1
- Node version: 18.9.1
- Browser name and version: Google Chrome latest version

Thank you for your help.

**Comment by colbyfayock** [comment]
Hi this is the wrong repository. I recommend you open an issue with Hygraph

https://github.com/hygraph/hygraph-examples

**Comment by Mart1n991** [comment]
Thank you for your response.
