### ISSUE TITLE
Handle Meta Tag Override With ClgOgImage

### ISSUE THREAD

**Issue by jamesqquick** [colbyfayock/next-cloudinary#167]
# **Feature Request**
Right now, using the `CldOgImage` component doesn't override matching properties in the Next.js `Head` component. 

## **Describe the solution you'd like**
I'd like to have default image properties set using the Next.js `Head` component, then have the `CldOgImage` component override those when applicable.

It seem like this can be done in Next.js by attaching keys to the individual meta tags. Next `Head` will automatically de-dupe multiple tags with the same key. Maybe you can add a default key to the meta properties `CldOgImage` component sets.

https://nextjs.org/docs/api-reference/next/head

**Comment by colbyfayock** [comment]
thoughts on this @jamesqquick ? https://github.com/colbyfayock/next-cloudinary/pull/171
