### ISSUE TITLE
[Feature] Overlay for Videos

### ISSUE THREAD

**Issue by lelouchB** [colbyfayock/next-cloudinary#186]
# **Feature Request**

At the moment, we can't add an overlay to CldVideoPlayer

## **Describe the solution you'd like**

It would be nice to have overlays/watermarks to videos

**Comment by colbyfayock** [comment]
hey @lelouchB check out this second example:

https://next-cloudinary-gsjwm4f2y-colbyfayock.vercel.app/components/cldvideoplayer/examples

thats what you had in mind right?

I'm using the `transformation` parameter for now and just passing it through

id like to eventually build a better API, like have an overlays= prop like CldImage, but for now, i wanted to get something together as i want to put more thought around that

gonna wait to get your eyes on this before i merge it :)

**Comment by lelouchB** [comment]
That's exactly what I needed
Thanks so much :)
