### ISSUE TITLE
Support full Cloudinary URLs as the `src` prop

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-cloudinary#2]
To make it easier for people to use, support grabbing the public ID from the src prop.

Example: 

```
<CldImage src="https://res.cloudinary.com/colbycloud-next-cloudinary/image/upload/images/turtle" />
```

**Comment by danielolaviobr** [comment]
O would like to tackle this issue as my first PR. Let me check if I understood what is expected. Currently the component only takes an id in  the src prop, and we want to now handle receiving the full uma url in the src prop? 

Question: Is the id in the image url that we want to support?

**Comment by colbyfayock** [comment]
@danielolaviobr yup! exactly.

```
<CldImage src="images/turtle" />
# vs
<CldImage src="https://res.cloudinary.com/colbycloud-next-cloudinary/image/upload/images/turtle" />
```

one thing to additionally think about is URLs may have transformations already applied, do we support those transformations? if so do we just take the full string of transformations and apply it as a raw effect? example:

```
<CldImage src="https://res.cloudinary.com/colbycloud-next-cloudinary/image/upload/w_100,h_100/images/turtle" />
```

here's a resource that may be helpful for breaking apart a Cloudinary URL: https://stackoverflow.com/a/67439513/844780

**Comment by danielolaviobr** [comment]
@colbyfayock I've been reading the code and tried to sketch some solutions that would apply the transformations in the url, but they looked quite complex. I'm thinking about getting the `publicId` from the url, and handle the image version as well, that if I understood well, represents what version of the image should be displayed.

So we would be able to receive something like this: 
```
<CldImage src="https://res.cloudinary.com/colbycloud-next-cloudinary/image/upload/w_100,h_100/v1/images/turtle" />
```
And transform it to this: 
```
<CldImage src="v1/images/turtle" />
```
And if the version is not present it will only use the regular `publicId`, that would be `images/turtle`.

The logic to get the transformations and apply them could discussed in a separate issue/PR, what do you think?

**Comment by colbyfayock** [comment]
that sounds great to me! I haven't tried passing in the version to the `cld.image` method before so curious if that passes in "as is" or not, if not we can handle the version in the next issue as well if needed

**Comment by colbyfayock** [comment]
also would you mind creating that separate Issue with the context? if you'd like to work on that after this happy to assign it as well, just lmk

**Comment by danielolaviobr** [comment]
Great, I'll open the issue. 

I've read a bit more about the version, and this line in the [docs](https://support.cloudinary.com/hc/en-us/articles/202520912-What-are-image-versions-) made me think if it is even possible to serve different version from the most recent one:

> When delivering assets from your Cloudinary account, only the newest copy of an asset is available for public delivery.

I've tried a couple of images with and without the version, and it worked fine, but the images were all the same. I couldn't tell if they were already the same or I was being served the same image regardless. I've tried testing it with my own images, but I couldn't get an image to change its version.

For now I will implement it with the version number, as it doesn't seem to break any behavior

**Comment by colbyfayock** [comment]
if im not mistaken i think the version may refer to the cached version, somewhat like a cache-busting mechanism, but i'm not 100% sure of that, but sounds great

**Comment by colbyfayock** [comment]
@danielolaviobr this one can be closed right? just confirming before i close it myself

**Comment by danielolaviobr** [comment]
Yeah, it can be closed
