### ISSUE TITLE
[Bug] Error: (0 , N.useState) is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by SwiftWinds** [colbyfayock/next-cloudinary#201]
# **Bug Report**

## **Describe the bug**

When trying to add:

```js
<CldImage
    className="block mr-2 max-w-full h-auto max-h-12 align-middle opacity-100"
    width="600"
    height="600"
    src="logos/nav"
    alt="Blockchain @ UCSB logo"
/>
```
with
 
```env
NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME="blockchainucsb"
``` 

in `.env.local`.

I get `Error: (0 , N.useState) is not a function or its return value is not iterable`.

## **Is this a regression?**

This is the first version I'm using `next-cloudinary` so I don't know

## **Steps To Reproduce the error**

1. `git clone https://github.com/SwiftWinds/reproduce-next-cloudinary-error.git`
2. `npm install`
3. `npm run dev`
4. observe error 

## **Expected behaviour**

There not to be an error

## **CodeSandbox or Live Example of Bug**

https://codesandbox.io/p/github/SwiftWinds/reproduce-next-cloudinary-error/draft/summer-bird

## **Screenshot or Video Recording**

<img width="1392" alt="image" src="https://github.com/colbyfayock/next-cloudinary/assets/12981958/289e92e0-9542-4953-a42c-5f3c7d42e39e">

### **Your environment**

- OS: macOS 12.6.5
- Node version: v20.1.0
- Npm version: v9.6.4
- Browser name and version: Microsoft Edge v113.0.1774.35

## **Additional context**

N/A

**Comment by colbyfayock** [comment]
hey @SwiftWinds unfortunately that codesandbox link doesnt work for me

are you using the Next.js 13 App directory?

if so, unfortunately for now, you need to add `"use client"` to the top of the file you're using the components in as it uses state

https://next-cloudinary.spacejelly.dev/guides/nextjs-13#app-router-app

i'm hoping to figure out a way to get this automatically embedded in the library but haven't figure out a way that doesnt create complications

**Comment by SwiftWinds** [comment]
I'm using the app directory. Somehow I added `"use client";` and it didn't work at first. Quitting and restarting `npm run dev` suddenly makes it work now (as long as I have `"use client";`). Thanks!
