### ISSUE TITLE
CldUploadWidget Only works Locally and not in Production.

### ISSUE THREAD

**Issue by Christianey** [colbyfayock/next-cloudinary#213]
# **Bug Report**

## **Describe the bug**

CldUploadWidget works perfectly fine locally but when I push to vercel, it shows an empty screen that keeps loading.

**Comment by colbyfayock** [comment]
hey @Christianey can you confirm your environment variables are set on your Vercel deployment?

**Comment by Christianey** [comment]
It's working now. My environment variables were set. I didn't change anything, just redeployed. Thanks for your swift response.

**Comment by Christianey** [comment]
One question please. Is there any way to make the upload widget upload only after clicking done. I do not like the way it uploads during preview. Thanks.

**Comment by colbyfayock** [comment]
@Christianey unfortunately that's not a customization option of the actual Upload Widget, which this is a wrapper of

https://cloudinary.com/documentation/upload_widget
