### ISSUE TITLE
Feedback for onError

### ISSUE THREAD

**Issue by ddaoxuan** [colbyfayock/next-cloudinary#216]
Hey guys, I'm keen to use CldImage component, but I can see the component itself takes control over NextJS onError prop function, and it actually never brings back the default behaviour of next, if poolling will never come back successful.

The question is, is it intended behaviour or shall it actually support native NextImage props aswell?

**Comment by colbyfayock** [comment]
hey i think this was an oversight - it should allow the caller to pass the onError prop as theyd typically expect in addition to the capabilities this component adds. ill get this fixed early next week

that should be the only prop that has that issue though, are you experiencing any other issues?

**Comment by colbyfayock** [comment]
hey @ddaoxuan as you probably saw, this is now available on the latest release. lmk if you run into any issues!
