### ISSUE TITLE
[Bug] use client error on dev mode

### ISSUE THREAD

**Issue by niku98** [colbyfayock/next-cloudinary#217]
# **Bug Report**

## **Describe the bug**

I got the following error when upgrade my Next version from **13.2.4** to **13.4.6**.

```ts
./src/components/DashboardLayout/index.tsx
ReactServerComponentsError:

The "use client" directive must be placed before other expressions. Move it to the top of the file to resolve this issue.

   ,-[/Users/phammanh/Projects/SelfProjects/nextjs-test/src/components/DashboardLayout/index.tsx:1:1]
 1 | import { jsxDEV as _jsxDEV } from "react/jsx-dev-runtime";
 2 | var _s = $RefreshSig$();
 3 | "use client";
   : ^^^^^^^^^^^^^
 4 | import { MenuOutlined } from "@ant-design/icons";
 5 | import { Grid } from "antd";
 6 | import { useMemo } from "react";
   `----

Import path:
  ./src/components/DashboardLayout/index.tsx
```

This is my component.

<img width="780" alt="Screenshot 2023-06-20 at 17 09 32" src="https://github.com/colbyfayock/next-cloudinary/assets/26998290/2b2af12b-51a5-4e91-a318-6029d28f005a">

## **Is this a regression?**

It still works on version **13.2.4**, but when I upgrade to higher version, the error appears.

## **Steps To Reproduce the error**

Use latest version of NextJS 13 with `app directory`

## **Screenshot or Video Recording**

<img width="977" alt="image" src="https://github.com/colbyfayock/next-cloudinary/assets/26998290/86d486f1-c30a-41b9-bc35-ccfe6b53adb9">

### **Your environment**

- OS: MacOs 13.2
- Node version: 19.1.0
- Npm version: 8.19.3
- Browser name and version: Chrome 114.0.5735.106

**Comment by colbyfayock** [comment]
hey @niku98 im not sure that this would be related to the library? I don't control where the "use client" directive goes and how its applied

do you see a potential issue with the library itself? if you remove next-cloudinary from that file, do you still get the error?

**Comment by colbyfayock** [comment]
this repository is for next-cloudinary, i would recommend asking this question in an appropriate place like the Next.js GitHub repository

**Comment by niku98** [comment]
> this repository is for next-cloudinary, i would recommend asking this question in an appropriate place like the Next.js GitHub repository

Sorry, my mistake 😄
