### ISSUE TITLE
[Bug] Url parsing only works for https, not http

### ISSUE THREAD

**Issue by lhguerra** [colbyfayock/next-cloudinary#224]
# **Bug Report**

When using cloudinary full url instead of public id, the component parses it fine if the link is https, but breaks if it uses http.

## **Steps To Reproduce the error**

1. Use the CldImage component with a cloudinary url with https
2. It will work fine
3. Change the image src to a Cloudinary url with http
4. The parsing will break and the whole url will be concatenated

## **Expected behaviour**

The same behavior no matter the protocol in the url

**Comment by colbyfayock** [comment]
thanks for the report @lhguerra this should be fixed momentarily on latest
