### ISSUE TITLE
[Bug] Unhandled runtime error when using CldImage component

### ISSUE THREAD

**Issue by smithmanny** [colbyfayock/next-cloudinary#227]
# **Bug Report**

## **Describe the bug**

Whenever I try and use the `CldImage` component on my Next JS 13 site (using pages) I get an error ```Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `he`.```

I'm using `next-cloudinary 4.13.1` and also `cloudinary 1.37.3` to delete images 

## **Is this a regression?**

Yes

14.12.0

## **Steps To Reproduce the error**

1. Install and setup next-cloudinary
2. Add component to file and page throws error

## **Screenshot or Video Recording**

<img width="1044" alt="image" src="https://github.com/colbyfayock/next-cloudinary/assets/1259332/e2f52195-5f9e-4a77-b442-50fc3d492eec">

### **Your environment**

- OS: Mac OSX 12.6
- Node version: Node 18
- Npm version: Yarn 1.22.19
- Browser name and version: Brave Browser 1.52.129

**Comment by colbyfayock** [comment]
hey @smithmanny glad to see it looks like you got this resolved, if this was some kind of issue with the component that i can make clear or easier to use, even if simply something in the docs, would love any feedback!

**Comment by smithmanny** [comment]
I found out that the problem came from updating next from 13.4.4 -> 13.4.9

**Comment by colbyfayock** [comment]
for anyone following along, im able to reproduce this: https://twitter.com/colbyfayock/status/1677783476014030849

im suspecting the issue is in how tsup is bundling or theres a bug in Next.js, not totally sure on this one at the moment

**Comment by colbyfayock** [comment]
looks like this is a known issue: https://github.com/vercel/next.js/issues/52216
