### ISSUE TITLE
[Bug] Possible race condition in iOS Safari when using CldUploadWidget

### ISSUE THREAD

**Issue by minirobotdan** [colbyfayock/next-cloudinary#249]
# **Bug Report**

## **Describe the bug**

When using iOS simulator to use the CldUploadWidget to upload an image, the image does not upload after clicking "Add". 

Interestingly, using the Safari remote debug tools and enabling break on all exceptions, the image uploads fine when stepping through the exceptions, making me think this might be a race condition of some kind.

## **Steps To Reproduce the error**

1. Open iOS Simulator (i used iPhone 14 Pro Max w/ iOS 16.4 but i'm not sure it matters)
2. Browse to https://next.cloudinary.dev/clduploadwidget/examples (originally discovered this bug on my own localhost but realised it works anywhere)
3. Click My Files and select any image
4. Click add, nothing happens, the image dialog closes and returns you to the widget menu

## **Expected behaviour**

Expect the image upload process to start with the selected image

## **Screenshot or Video Recording**

[](https://github.com/colbyfayock/next-cloudinary/assets/1784933/da8d72d3-e0b9-4684-bed7-df68d2e8ee1e)

### **Your environment**

- All that's required is iOS Simulator (iPhone 14 Pro Max w/ iOS 16.4)
- Discovered on a Mac Studio M1 Ventura 13.4.1 (c)

**Comment by colbyfayock** [comment]
hey @minirobotdan - i was able to reproduce this as well in the sim both on next.cloudinary.dev as well as the official Cloudinary docs: https://cloudinary.com/documentation/upload_widget

that said, testing it on my phone, it works fine, have you tried on an actual device? just wanted to confirm your experience

i dont think this is a bug with Next Cloudinary and I'm guessing it'll be low priority as it may simply be a Sim complication, but i'll ask the team if they have any ideas why that would happen

**Comment by minirobotdan** [comment]
@colbyfayock sorry I totally missed the notification for this. You're absolutely right it seems to be a sim specific issue, sorry I hadn't looked any further into it. Will close the issue as it will probably come out in the wash in a future sim build.
