### ISSUE TITLE
[Bug] Cloudinary.UploadWidget - encountered error !  DOMException: Failed to execute 'postMessage' on 'Window

### ISSUE THREAD

**Issue by haraldini** [colbyfayock/next-cloudinary#259]
# **Bug Report**

## **Describe the bug**

The Uploadwidget throws a DOM error when opened

```
Cloudinary.UploadWidget - encountered error !  DOMException: Failed to execute 'postMessage' on 'Window': open(t,e){return y(t,e),this} could not be cloned.
    at Object.I [as postMessage] (https://widget.cloudinary.com/v2.0/global/all.js:1:118510)
    at Object.i [as sendMessage] (https://widget.cloudinary.com/v2.0/global/all.js:1:125177)
    at https://widget.cloudinary.com/v2.0/global/all.js:1:124417
    at https://widget.cloudinary.com/v2.0/global/all.js:1:124194
    at https://widget.cloudinary.com/v2.0/global/all.js:1:124200
```

## **Steps To Reproduce the error**

1. Go to next examples: https://next.cloudinary.dev/clduploadwidget/basic-usage
2. Click button "Upload an image"
3. Error thrown in console

## **Expected behaviour**
No error

**Comment by satyajitnayk** [comment]
Facing the same error @colbyfayock @haraldini @kbravh 
```javascript
app-index.js:31 Cloudinary.UploadWidget - encountered error !  DOMException: Failed to execute 'postMessage' on 'Window': open(t,e){return y(t,e),this} could not be cloned.
    at Object.I [as postMessage] (https://widget.cloudinary.com/v2.0/global/all.js:1:118510)
    at Object.i [as sendMessage] (https://widget.cloudinary.com/v2.0/global/all.js:1:125177)
    at https://widget.cloudinary.com/v2.0/global/all.js:1:124417
    at https://widget.cloudinary.com/v2.0/global/all.js:1:124194
    at https://widget.cloudinary.com/v2.0/global/all.js:1:124200

```

URL to check error in console: https://airbnb-lite-psi.vercel.app/
Video to reproduce:  https://github.com/colbyfayock/next-cloudinary/assets/32722867/ba0a1658-64cd-478a-a506-64b1819999d7
refer code: https://github.com/satyajitnayk/airbnb-light/blob/main/app/components/inputs/ImageUpload.tsx#L29

**Comment by raihan-ramadhan** [comment]
this error make my app just can upload once after that i need to reload again, it can be done with deupgrade to next-cloudinary@4.16.3, but i can't use onSuccess feature in that version

**Comment by colbyfayock** [comment]
hey all, have a fix in, going to test it again in the morning before merging it in, but looks like it was just a silly mistake that's easily fixed. i appreciate your patience on this
