### ISSUE TITLE
Using Next Cloudinary or something similar in an Astro app

### ISSUE THREAD

**Issue by jamesgrubb** [colbyfayock/next-cloudinary#260]
Hi hoped to use this in an Astro project. Would there be allot of work for me to adapt it? Thanks

**Comment by colbyfayock** [comment]
hey @jamesgrubb i hope to eventually create an Astro equivalent, but for now you have a few options

We also have [Svelte Cloudinary](https://svelte.cloudinary.dev/), which Astro supports Svelte components, so theoretically you should be able to use that within your Astro app

Svelte Cloudinary and [Nuxt Cloudinary](https://cloudinary.nuxtjs.org/) both currently rely on [Unpic](https://unpic.pics/img/) to fill in the whole where this package uses Next Image. It's the underlaying component that we pass a Cloudinary URL into that allows us to not have to manage all the <img element optimizations and just pass in a constructed URL based on transformation props

They also both use a package I created [Cloudinary Util](https://github.com/colbyfayock/cloudinary-util) which has a [URL Loader](https://github.com/colbyfayock/cloudinary-util/tree/main/packages/url-loader) module that allows you to easily construct a Cloudinary URL using the same API you get from the props:

```
constructCloudinaryUrl({
  options: {
    src: 'my-public-id',
    width: 800,
    height: 600
  },
  config: {
    cloud: {
      cloudName: 'my-cloud'
    }
  }
});
```

You can see the source for in both packages:
* https://github.com/cloudinary-community/svelte-cloudinary/blob/main/svelte-cloudinary/src/lib/components/CldImage.svelte
* https://github.com/nuxt-modules/cloudinary/blob/main/src/runtime/components/CldImage.vue

Ultimately it works along the lines of:

```
<Image
 ...imageprops 
  transformer={(width) => {
    // combine component props and options, normalize width
    return constructCloudinaryUrl(options, config)
  }}
/>
```

If you end up trying one of these methods id love to hear about your experience! and happy to answer any questions
