### ISSUE TITLE
[Feature] Widget Instance Method Options

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-cloudinary#262]
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

The instance methods that were added should be able to pass in options per their documented ability

**Comment by colbyfayock** [comment]
hey yup! we're talking about CldUploadWidget here. here's a bit more info...

Cloudinary supports a variety of instance methods: https://cloudinary.com/documentation/upload_widget_reference#instance_methods

Different methods support passing in different options to those methods and i want to be able to support the options for each method

currently, each of these methods are defined here: https://github.com/colbyfayock/next-cloudinary/blob/main/next-cloudinary/src/components/CldUploadWidget/CldUploadWidget.tsx#L160

they use a shared function to help sanely manage some of the logic without repeating it through each one, then ultimately passed into the callback to make them available: https://github.com/colbyfayock/next-cloudinary/blob/main/next-cloudinary/src/components/CldUploadWidget/CldUploadWidget.tsx#L239

and exposing it in the child prop: https://github.com/colbyfayock/next-cloudinary/blob/main/next-cloudinary/src/components/CldUploadWidget/CldUploadWidget.tsx#L254

let's take `close` for instance, which takes a parameter of `quiet` as to whether or not to well, close quietly. i want to be able to support passing in that specific option to that method

we also want to make sure this is all type-supported, which needs to be fleshed out and supported as makes sense: https://github.com/colbyfayock/next-cloudinary/blob/main/next-cloudinary/src/components/CldUploadWidget/CldUploadWidget.types.ts#L44

does that make sense? are you interested in working on this?

**Comment by msk4862** [comment]
yes I would like to give it a try, Thanks for the detailed explanation.
Will update about the progress.

**Comment by colbyfayock** [comment]
Assigned!

**Comment by msk4862** [comment]
I have one more doubt: If I'm understanding it correctly while calling these methods from child props (for example: [from here](https://github.com/colbyfayock/next-cloudinary/blob/29479f20e827cd2bff19c230d6a745cf1693ec65/next-cloudinary/src/components/CldUploadButton/CldUploadButton.tsx#L63)), eventually [invokeInstanceMethod](https://github.com/colbyfayock/next-cloudinary/blob/29479f20e827cd2bff19c230d6a745cf1693ec65/next-cloudinary/src/components/CldUploadWidget/CldUploadWidget.tsx#L150) is getting called which then calls the particular instance [method from here](https://github.com/colbyfayock/next-cloudinary/blob/29479f20e827cd2bff19c230d6a745cf1693ec65/next-cloudinary/src/components/CldUploadWidget/CldUploadWidget.tsx#L156C7-L156C31), but here while calling there is no argument passed to the method. 
So my question is the params we pass while calling these instance methods [from here](https://github.com/colbyfayock/next-cloudinary/blob/29479f20e827cd2bff19c230d6a745cf1693ec65/next-cloudinary/src/components/CldUploadButton/CldUploadButton.tsx#L63)), how do they get relayed?

**Comment by colbyfayock** [comment]
yup what you said makes sense, and thats a good question

i was originally going to suggest the `arguments` keyword but that doesnt seem to work due to how the upload widget uses an iframe and the communication methods associated with it

it's a bit "hacky" but because we're only ever expecting 2 arguments, we could consider doing two explicitly defined options as a stopgap solution to support it:

```
  function open(one: any, two: any) {
    invokeInstanceMethod('open', [one, two]);
```
```
  function invokeInstanceMethod(method: string, options?: any) {

    if (!widget.current) {
      widget.current = createWidget();
    }

    if ( typeof widget?.current[method] === 'function' ) {
      widget.current[method](options[0], options[1]);
```

i dont think this is an ideal solution but it works

i'm open to ideas around how to handle this including refactoring anything in there, for instance, if you feel that `invokeInstanceMethod` isn't helping and just getting in the way, each method can be individually defined, but was trying to clean things up a bit with it

what do you think?

**Comment by msk4862** [comment]
okay, make sense.
I've made changes accordingly, but I'm not sure how can I test the functionality if nothing is breaking. I did ran the [tests script](https://github.com/colbyfayock/next-cloudinary/blob/60c4b7c895056e2abf0a0f7aec54b0a3bdd04cb8/next-cloudinary/package.json#L14), and tests are passing now.
