### ISSUE TITLE
[Bug] Cloudinary upload widget loads forever

### ISSUE THREAD

**Issue by SwiftWinds** [colbyfayock/next-cloudinary#263]
# **Bug Report**

## **Describe the bug**

When using `<CldUploadButton uploadPreset="companies_unsigned" />`, the upload widget, once one clicks "Upload", it just loads forever.

Code example: https://github.com/data-science-ucsb/ds-career-fair/blob/e7d7773bb79d72da1c33afa0c584e68b69c46d82/app/page.tsx#L61

## **Expected behaviour**

For it to eventually load and show the upload widget UI

## **Screenshot or Video Recording**

https://jmp.sh/GXRqBKIB

### **Your environment**

- next-cloudinary: v4.18.1
- OS: macOS 13.5.1
- Node version: v20.4.0
- Npm version: v9.8.1
- Browser name and version: Microsoft Edge v116.0.1938.54

**Comment by SwiftWinds** [comment]
Silly mistake, just forgot to add the `NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME` to the `.env.local` 🤦 . Thanks for the fantastic library!

**Comment by colbyfayock** [comment]
ah thanks for following up. i probably should check that its set and throw an error / warning if its not
