### ISSUE TITLE
[Bug] CldImage not working with Next 13.4.19

### ISSUE THREAD

**Issue by nk9** [colbyfayock/next-cloudinary#278]
# **Bug Report**

## **Describe the bug**

I am using `CldImage` like this:

```
            <CldImage
                height={180}
                width={180}
                src="samples/bike"
            />
```

This was fine in 13.3, but then I upgraded to 13.4.9. And now I'm getting lots of errors ass soon as the `CldImage` component is added to the DOM:

```
The above error occurred in the <Ce> component:

Check the render method of `Ce`.
Ce@webpack-internal:///./node_modules/next-cloudinary/dist/index.mjs:20:2076
Test
ThemeProvider@webpack-internal:///./node_modules/@mui/private-theming/ThemeProvider/ThemeProvider.js:45:7
ThemeProvider@webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:57:7
ThemeProvider@webpack-internal:///./node_modules/@mui/material/styles/ThemeProvider.js:26:9
MyApp@webpack-internal:///./pages/_app.js:33:77
PathnameContextProviderAdapter@webpack-internal:///./node_modules/next/dist/shared/lib/router/adapters.js:80:42
ErrorBoundary@webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:306:63
ReactDevOverlay@webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:858:908
Container@webpack-internal:///./node_modules/next/dist/client/index.js:78:1
AppContainer@webpack-internal:///./node_modules/next/dist/client/index.js:182:24
Root@webpack-internal:///./node_modules/next/dist/client/index.js:372:35
```

## **Is this a regression?**

This was fine in 13.3.34, but fails on 13.4.9. I'm using next-cloudinary 4.10.0.

## **Steps To Reproduce the error**

1. Upgrade to the current version of Next, 13.4.9
2. Maaaaaybe `withEmotionCache` has something to do with it? You might need to be using MUI, not sure.
3. Create and load this page:

*test.js*
```
import { CldImage } from 'next-cloudinary';

export default function Test() {
    return (
        <CldImage
            height={180}
            width={180}
            src="samples/bike"
        />
    )
}
```
## **Expected behaviour**

CldImage to work like before

## **CodeSandbox or Live Example of Bug**

I'll have a look and see if I can get CodeSandbox displaying the behavior.

### **Your environment**

- OS: 
- Node version: 18.6.0
- Npm version: 9.5.1
- Browser name and version: Firefox 116.0.3
- @emotion/cache: 11.10.8
- @mui/material: 5.12.3

**Comment by colbyfayock** [comment]
hey @nk9 thanks for a report. A codesandbox here would be really helpful, as it seems to be failing with pretty basic functionality 😢 

also given the tracing in there, it looks like mui is involved

if i can get a full picture i can try to debug and see what's going on
