### ISSUE TITLE
[Bug] Stop generating CldVideoPLayer ID using Math.random

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-cloudinary#281]
# **Bug Report**

## **Describe the bug**

Stop generating CldVideoPLayer ID using Math.random

Creating issues between server and client

Can we add a warning instead? Perhaps we would need to track the IDs being used in a top level scoped object?

## **Steps To Reproduce the error**

1.
2.
3.
4.

### **Your environment**

- OS: 
- Node version:
- Npm version:
- Browser name and version:

**Comment by rafaelderolez** [comment]
Found this issue because I'm getting this error:
Warning: Prop `id` did not match. Server: "player-samples-sea-turtle-76873" Client: "player-samples-sea-turtle-13646"

**Comment by JoshuaRotimi** [comment]
@colbyfayock I'm interested in working on this. What would be a better option for generating the ID. I'm not sure using a unique ID generating library for this purpose alone is ideal. I would love your input. Thanks.

**Comment by colbyfayock** [comment]
@JoshuaRotimi that sounds good!

my original idea with the randomized ID is I would have loved to avoid someone having to add an `id` field just to allow them to add multiple instances of the same video on the same page, but it seems that there's no reliable way to do that right now

so that said, here's my current thinking

i think we need to set up the ID to remove the `idRef` value, so that it only uses the public ID.

however, if someone has 2 of the same video on the page, this will cause it to not work properly with different settings (such as having two different color themes)

so let's create a module-scoped variable, let's say `playerInstances` for example, that stores that new player ID and checks if it already exists. if it already exists, add a `console.warn` stating something like:

> Multiple instances of the same video detected on the page which may cause some features to not work. Try adding a unique `id` to each player.

if the person is adding the ID, playerId will be that value, so that warning should not show

what do you think? does that make sense?

**Comment by JoshuaRotimi** [comment]
Ohh alright. I understand the suggested approach. That makes sense. You can assign it to me and I will make the PR

**Comment by colbyfayock** [comment]
awesome thanks!
