### ISSUE TITLE
Allow CldVideoPlayer Fully Extend Cloudinary Video Player API reference Paramenters and Props

### ISSUE THREAD

**Issue by DevYemi** [colbyfayock/next-cloudinary#283]
# **Feature Request**
I would like to be able to hide the context Menu when a user right clicks on the video as per the information in the cloudinary docs [https://cloudinary.com/documentation/video_player_api_reference](url)

## **Is your feature request related to a problem? Please describe.**
No it's not

One of the rich advantage of Cloudinary Video player is the ability to customize alot of the video player features and UI but this package seem to restrict dev ability to do that. will it be possible for all the Parameters in the video Player API here [Here](https://cloudinary.com/documentation/video_player_api_reference) be also be availible as props that can be passed to CldVideoPlayer Component

## **Describe the solution you'd like**
Aside the default props type currently implemented in the CldVideoPlayer  Component also make the CldVideoPlayer accept props type that as a schema like in the cloudinary Video Player API docs [Here](https://cloudinary.com/documentation/video_player_api_reference), where we have:
- PlayerVisiuals props containing [Player visuals Props](https://cloudinary.com/documentation/video_player_api_reference#player_visuals)
- PlayerBehaviour Props containing [Player behavior Props](https://cloudinary.com/documentation/video_player_api_reference#player_behavior)
- VideoConfig Props containing [Video config Props](https://cloudinary.com/documentation/video_player_api_reference#video_config)
- AdsAndAnalytics Props containing [Ads and analytics Props](https://cloudinary.com/documentation/video_player_api_reference#ads_and_analytics)
- AdProps Containing [AdsProps](https://cloudinary.com/documentation/video_player_api_reference#adsprops)
- PlaylistWidgetProps containing [PlaylistWidgetProps](https://cloudinary.com/documentation/video_player_api_reference#playlistwidgetprops)

All the props i mentioned above will be included in the `CloudinaryVideoPlayerOptions` type and spread in the `playerOptions` object that will eventually be used to instantiate the videoPlayer in the codebase here ` playerRef.current = cloudinaryRef.current.videoPlayer(videoRef.current, playerOptions);`.

So we should now have:
````
let playerOptions: CloudinaryVideoPlayerOptions = {
        //default props
       
      {...spread-the-props-i-listed-here}
      };
````

## **Additional context**
I'm willing to help work on this if needed, thanks for the work you do.

**Comment by colbyfayock** [comment]
hey @DevYemi thanks for reporting - definitely a lot of opportunity to add features here

would you be interested then in helping with a pull request? a nice little bonus is given it's currently Hacktoberfest, you can get some swag :) https://cloudinary.com/blog/hacktoberfest-celebrate-open-source-sdks

**Comment by JoshuaRotimi** [comment]
I'd also be interested in working on this if @DevYemi is not already on it.

**Comment by colbyfayock** [comment]
thanks @JoshuaRotimi - let's see what they have to say first only because they offered to work on it in the Additional context, but if not, it's all yours!

**Comment by colbyfayock** [comment]
@JoshuaRotimi if you still wanted tow ork on this you can claim it

**Comment by DevYemi** [comment]
@colbyfayock Hey so sorry i didn't you had responed to this. I will be taking this up and be working on it this week.

@JoshuaRotimi we can work on this together too

**Comment by colbyfayock** [comment]
sounds good - keep in mind, to qualify for Hacktoberfest, you need to have a PR opened by tomorrow. As long as it finishes the majority of the work it can be considered eligible, even if i need to request fixes / changes

**Comment by DevYemi** [comment]
Noted @colbyfayock, thank you
