### ISSUE TITLE
[Bug] TypeError: "gravity" is read-only

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-cloudinary#29]
### **Describe the bug**

When trying to use a custom `crop` without setting a gravity, you get an error `TypeError: "gravity" is ready-only`

### **Is this a regression?**

Unsure

### **Steps To Reproduce the error**

```
<CldImage width="..." height="..." src="..." crop="crop" />
```

### **Expected behaviour**

Gravity should default to `auto` when not set

### **Media proof (Screenshot)**

![image](https://user-images.githubusercontent.com/1045274/195945293-c6e9955d-7798-45f1-aa75-5fb6b8366592.png)

### **Additional context**

Tests should be added for the cropping plugin

**Comment by Smartmind12** [comment]
Can i work on this issue??

**Comment by colbyfayock** [comment]
all yours!

**Comment by Smartmind12** [comment]
@colbyfayock we can use g-auto as a command in it right??

**Comment by colbyfayock** [comment]
the bug will likely be in here 😉 https://github.com/colbyfayock/next-cloudinary/blob/ae070253f067cd5dd35e1cbc3c578940e4d04f68/next-cloudinary/src/plugins/cropping.js
