### ISSUE TITLE
[Feature] Allow user to override NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME

### ISSUE THREAD

**Issue by PfisterFactor** [colbyfayock/next-cloudinary#290]
# **Feature Request**

It would be nice if we could allow the user to specify the cloud name when using the component.

## **Is your feature request related to a problem? Please describe.**

I want to be able to dynamically select the cloud name when creating the component.

## **Describe the solution you'd like**

Have the cloud name specified in the config parameter in `CldImage` be used if specified.

## **Describe alternatives you've considered**

There's not too many, as NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME is replaced at build time with the cloud name, so it is hard coded

See my [PR](https://github.com/colbyfayock/next-cloudinary/pull/291)

**Comment by colbyfayock** [comment]
Closed by #291
