### ISSUE TITLE
[Feature] Adaptive streaming

### ISSUE THREAD

**Issue by lucastonon** [colbyfayock/next-cloudinary#302]
When I set the streaming_profile to auto, the player shows the error **Video cannot be played- Invalid Transformation - Streaming profile not supported for non-streaming formats**

`transformation={{streaming_profile: 'auto'}}`

But I can't seem to be able to set the format to hls.
Is it possible to set sourceType?

**Comment by colbyfayock** [comment]
not yet, but i'll get this added! https://cloudinary.com/documentation/video_player_hls_dash#specify_the_streaming_format_and_streaming_profile
