### ISSUE TITLE
Infinite error loop when browser tries to load unsupported image

### ISSUE THREAD

**Issue by fourwordsnz** [colbyfayock/next-cloudinary#303]
It is my first time using Next Cloudinary Image, together with _f_auto_ prop in the component.

An unexpected issue I ran into was testing components with the iPhone emulator on Chrome Dev Tools. 

Chrome doesn't support j2 images, which results in an infinite request loop (using bandwidth).

I didn't realise it was returning j2 for a while, and I initially thought it was an issue with the component. It would be helpful to add this to the documentation highlighting this. 

https://support.cloudinary.com/hc/en-us/community/posts/8617513283218-Cloudinary-f-auto-serve-jp2-files-in-Chrome-not-support-

https://cloudinary.com/documentation/image_optimization#automatic_format_selection_f_auto

**Comment by colbyfayock** [comment]
i even attempted to set a customer UA using the built-in iphone ones but also tried to set an old custom one in case i can't because i think latest safari supports AVIF, so i assume thats why we serve that

<img width="1526" alt="image" src="https://github.com/colbyfayock/next-cloudinary/assets/1045274/adebccac-aa2f-420c-9580-3629a872c65e">

**Comment by colbyfayock** [comment]
hey @fourwordsnz keep me updated on if this impacted your billing so i can see if i can offer a solution

but i put together a fix for this that i believe is an issue with the error handling in the component: https://github.com/colbyfayock/next-cloudinary/pull/305

im going to review this again a bit later to make sure im not missing anyhing but this should totally address the issue, though ill still add a line of documentation as to why an image might not work

perhaps i could add a backup feature later of serving a more widely available format like jpg 🤔  but thinking that's out of scope and need to think more on that
