### ISSUE TITLE
NPM shows no license

### ISSUE THREAD

**Issue by villesau** [colbyfayock/next-cloudinary#321]
Looks like the license is not carried over to NPM: https://www.npmjs.com/package/next-cloudinary

Maybe a packaging issue?

<img width="1393" alt="Screenshot 2023-10-22 at 23 32 11" src="https://github.com/colbyfayock/next-cloudinary/assets/2647016/812b60ee-b3d5-4533-bea2-9b7d8b6d1732">

**Comment by colbyfayock** [comment]
thanks for flagging htis @villesau should be addressed in the upcoming release
