### ISSUE TITLE
[Feature] Change poster of CldVideoPlayer

### ISSUE THREAD

**Issue by farhangDatafinery** [colbyfayock/next-cloudinary#322]

**Comment by khushi2502** [comment]
Hey, can you elaborate your issue?

**Comment by khushi2502** [comment]
To change the poster of a video in Next Cloudinary, we can use the poster transformation parameter. 
The poster parameter allows us to specify a frame from the video to use as the poster image.

To use the poster parameter, we can either add it to the URL of the video or we can use the Cloudinary transformation API.

To add the poster parameter to the URL of the video, simply append the following to the URL:

?poster=<start_offset>

Where <start_offset> is the offset of the frame in seconds. For example, to use the frame at the 5 second mark as the poster image, we would use the following URL:

https://res.cloudinary.com/my-cloud-name/video/upload/my-video.mp4?poster=5
To use the poster parameter with the Cloudinary transformation API, we would use the following code:
`
const cloudinary = require('cloudinary');

const transformation = cloudinary.Transformation.apply({
  poster: 5
});

const url = cloudinary.url('my-video.mp4', transformation);
`

Once we have the URL of the video with the poster parameter, we can use it in our Next application. For example, we could use it in an img tag to display the poster image:
`
<img src={url} alt="Video poster" />
`

Example
`
// Next.js code
import Image from 'next/image';

const VideoPoster = () => {
  const url = `https://res.cloudinary.com/my-cloud-name/video/upload/my-video.mp4?poster=5`;
  return (
    <Image
      src={url}
      alt="Video poster"
      width={100}
      height={100}
    />
  );
};

export default VideoPoster;
`


This code will display the poster image from the video at the 5 second mark.

The poster transformation parameter is a simple way to change the poster of a video in Next Cloudinary. We can use it to create custom video posters that highlight a specific part of the video.

**Comment by colbyfayock** [comment]
@farhangDatafinery i dont believe i currently have this exposed, but i'll get this added soon

**Comment by colbyfayock** [comment]
hey @farhangDatafinery poster is now available on the player, would love for you to try it out and let me know how it goes!

docs are updated: 
- https://next.cloudinary.dev/cldvideoplayer/configuration
- https://next.cloudinary.dev/cldvideoplayer/examples#poster

as well as a few examples on the PR: https://github.com/colbyfayock/next-cloudinary/pull/337
