### ISSUE TITLE
[Feature] Support "Strict Transformations" together with "Named Transformations"

### ISSUE THREAD

**Issue by stenkast** [colbyfayock/next-cloudinary#324]
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

I've run into a bit of a problem with the component CldImage when strict transformations is enabled. Because the component forces c_limit from what I can tell, as well as the required width & height properties, it doesn't satisfy strict transformations when paired with a named transformation. 

## **Describe the solution you'd like**

I think the most basic solution would be a boolean named "strictTransformations", and have it default to false to not cause issues for people, and when it's set to true, it doesn't put the c_limit, width and height into the generated URL. 

## **Additional context**

URL the component generates: 
`https://res.cloudinary.com/blabla/image/upload/c_limit,w_176/t_gallery-thumbnail/cld-sample`

URL required by strict transformations with my named transformation:
`https://res.cloudinary.com/blabla/image/upload/t_gallery-thumbnail/cld-sample`

**Comment by colbyfayock** [comment]
thanks @stenkast - just to clarify,  would you expect then that t his would also bypass any responsive images? so if for instance you did:

```
<CldImage transformations=['my-transformation'] strictTransformations />
```

it would literally only be the named transformation like your example?

**Comment by stenkast** [comment]
> thanks @stenkast - just to clarify, would you expect then that t his would also bypass any responsive images? so if for instance you did:
> 
> ```
> <CldImage transformations=['my-transformation'] strictTransformations />
> ```
> 
> it would literally only be the named transformation like your example?

I'm not sure what you mean exactly with bypassing responsive images. If the responsive images you're talking about would work with strict transformations on when used with this component then I don't see why they should be bypassed too.

The specific use-case that I ran into is that it just forced c_limit, width and height into the image src URL which would not work in my specific scenario because of strict transformations. So when I manually removed those properties from the URL it worked fine.

My named transformation already handled the width and height, and so it was just redundant properties that broke a URL and I couldn't prevent it.

**Comment by colbyfayock** [comment]
i'm mostly trying to determine how restrictive i need to be from the transformation side

the CldImage component has responsive sizing built in that works via transformations: https://next.cloudinary.dev/guides/responsive-images

but im thinking that those transformations, not generated eagerly or by named transformations, would not work

i'm trying to do some digging on my end to make sure i'm properly supporting this feature whether that's literally only allowing named transformations or if we can expose more. perhaps an MVP is only allowing named transformations

will report back once i have more info

**Comment by colbyfayock** [comment]
@stenkast let me know if you run into any issues!
