### ISSUE TITLE
[Feature] Add support for NextJS 14

### ISSUE THREAD

**Issue by birdzai** [colbyfayock/next-cloudinary#328]
# **Feature**

## **Add support for NextJS 14**

After upgrading to NextJS 14, adding a new dependency with pnpm results in the following warning:

 WARN  Issues with peer dependencies found
.
└─┬ next-cloudinary 4.28.0
  └── ✕ unmet peer next@"^12 || ^13": found 14.0.0

## **Steps To Reproduce the error**

1. Upgrade to NextJS 14
2. Perform an action with pnpm

## **Expected behaviour**

No pnpm warning issued

**Suggested Fix:**

Update peer-dependencies in package.json:

"next": "^12 || ^13 **|| ^14"**

### **Your environment**

- OS: MacOS Sonoma V14.1
- Node version: 20.9.0
- Npm version: 10.2.1
- NextJS version: 14.0.0

**Comment by colbyfayock** [comment]
thanks @birdzai working on getting this updated

looks like a new type was introduced that I'll need to resolve, wasn't just a simple peer update

<img width="1126" alt="image" src="https://github.com/colbyfayock/next-cloudinary/assets/1045274/73575169-d975-4429-a1ff-ddd37d673300">

also looks like this will need to be a breaking change as minimum node version is now 18.17

https://nextjs.org/blog/next-14#other-changes

**Comment by birdzai** [comment]
Thanks @colbyfayock .... as for minimum node version now being 18.17, kind of makes sense as I see that Node 20 is now LTS, do dropping V16 is in line with only maintaining support for the last 2 LTS versions.
