### ISSUE TITLE
[Feature] Improve Readme images

### ISSUE THREAD

**Issue by 3t8** [colbyfayock/next-cloudinary#33]
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

The Next.js image in the current README is hardly visible if using dark mode

![dark_mode](https://user-images.githubusercontent.com/62209650/196503670-b0175340-cc2a-470f-a360-14e8da54695c.png)

## **Describe the solution you'd like**

It would be nice to have the image change dynamically, adapting to the user's theme

![light_mode](https://user-images.githubusercontent.com/62209650/196504443-b0c1f430-22d5-42a3-8e93-13d1b7832452.png)
![dark_mode](https://user-images.githubusercontent.com/62209650/196504209-e9d00a67-8d2b-46b2-846d-be2dcf3c2ac2.png)

I'd be more than happy to work on it if it gets approved

**Comment by colbyfayock** [comment]
you may want to make the cloudinary logo use the white version as well for  dark mode

https://cloudinary.com/assets

**Comment by 3t8** [comment]
@colbyfayock I added dark mode to both logos #34
