### ISSUE TITLE
[Bug] CldUploadWidget modal overflow on medium screens

### ISSUE THREAD

**Issue by RemiZlatinis** [colbyfayock/next-cloudinary#332]
# **Bug Report**

## **Describe the bug**

On a medium size screen that has a high resolution the options ("My Files", "Web Address", etc.) of the CldUploadWidget modal aren't visible. The modal is overflowing.

## **Steps To Reproduce the error**

This behaviour can be simulated by zoom-in or by increasing the "Scale" on the display.

## **Expected behaviour**

The content panel should be shrinking. 

## **Screenshot or Video Recording**
![Screenshot 2023-10-29 024107](https://github.com/colbyfayock/next-cloudinary/assets/39838694/cf26852a-e645-426a-abfc-993e41b58064)

### **Your environment**
- OS: Windows 22H2
- Node version: 21
- Npm version: 8
- Browser name and version: Edge v118

**Comment by colbyfayock** [comment]
quick update - it's an issue we're tracking but i dont have any estimate on when it may be fixed

a colleague had an interesting workaround that uses max-width along with viewport height to make it collapse into the mobile view when the height is too small: https://codesandbox.io/s/h3hc3k?file=/styles.css:32-52

unfortunately there's nothing i can really do here, so going to close this, but hope that can help

**Comment by RemiZlatinis** [comment]
It would be great if we could use it without relying on junky solutions. For now, this is an acceptable workaround. Anyway, thank you for your time. 🫡
