### ISSUE TITLE
CldImage Default Image

### ISSUE THREAD

**Issue by ShaneDigi400** [colbyfayock/next-cloudinary#340]
How can we use the default image feature in Cloudinary with CldImage?

https://cloudinary.com/documentation/advanced_url_delivery_options#using_a_default_image_placeholder

**Comment by colbyfayock** [comment]
hey @ShaneDigi400 i dont think this is implemented, but I'll work on getting it in within the next few days (or sooner)

**Comment by colbyfayock** [comment]
hey @ShaneDigi400 available in the latest release

https://next.cloudinary.dev/cldimage/configuration#deliverytype

let me know if you run into any issues

**Comment by sethburtonhall** [comment]
I am experiencing an issue with this ... any ideas? Thank you in advance.

```
<CldImage
	src="public_id" 	// displays the correct cloudinary image when the public_id exists, BUT does not display the defaultImage below with the public_id does not exist(loads a broken image and displays alt text).
	width={805}
	height={919}
	alt="image alt text"
	defaultImage="https://res.cloudinary.com/cloudname/image/upload/public_id.png"
/>
```

**Comment by colbyfayock** [comment]
hey @sethburtonhall strange, i was able to get it working on the docs homepage with:
```
<CldImage
  width="987"
  height="1481"
  src={`${process.env.IMAGES_DIRECTORY}/asdf`}
  defaultImage={`${process.env.IMAGES_DIRECTORY}/turtle.jpg`}
  sizes="50vw"
  alt="Original image of woman with headphones"
  priority
/>
```

can you share the URL that's generated with this format `defaultImage="public_id.png"`?

it doesn't accept URL format at this time

**Comment by sethburtonhall** [comment]
> hey @sethburtonhall strange, i was able to get it working on the docs homepage with:
> 
> ```
> <CldImage
>   width="987"
>   height="1481"
>   src={`${process.env.IMAGES_DIRECTORY}/asdf`}
>   defaultImage={`${process.env.IMAGES_DIRECTORY}/turtle.jpg`}
>   sizes="50vw"
>   alt="Original image of woman with headphones"
>   priority
> />
> ```
> 
> can you share the URL that's generated with this format `defaultImage="public_id.png"`?
> 
> it doesn't accept URL format at this time

Hey @colbyfayock All is good now, your comment helped me realize that I had the wrong public_id. Thanks!!!
