### ISSUE TITLE
[Bug] AspectRatio prop ignored?

### ISSUE THREAD

**Issue by ColbyMay** [colbyfayock/next-cloudinary#352]
# **Bug Report**

## **Describe the bug**

Adding `fill={true}` and the `aspectRatio={'1.1'}` does not seem to alter the transformed URL atall. Also tried with just numerals as well as placing the prop inside 
`effects={[
     aspectRatio={1.1}
]}`
## **Is this a regression?**

I am unsure if this worked previously as this is my first time using this library.

## **Steps To Reproduce the error**

1.add aspectRatio prop into <CldImage/> component
2.Check rendered Cloudinary URL and see that ar_ is not added to url string

## **Expected behaviour**

props to the <CldImage/> component related to Cloudinary transformations should convert media URL to the intended prop values

### **Your environment**

- OS: macOS 13.4 (22F66)
- Node version: 18
- Npm version: 9.5.1
- Browser name and version: Chrome Version 119.0.6045.159 (Official Build) (x86_64)

**Comment by colbyfayock** [comment]
hey @ColbyMay confirming this looks to be a bug

the aspectRatio option appears to only be available in overlays and underlays right now, which is incorrect: https://github.com/search?q=repo%3Acolbyfayock%2Fcloudinary-util%20primary&type=code

i'll work on getting a fix for this, but it should be available both as a top-level prop and within the effects array

**Comment by colbyfayock** [comment]
also just wanted to add, what are your expectations for how `fill` modifies the Cloudinary URL? 

`fill` specifically refers to the Next.js Image `fill` prop, which isn't related to Cloudinary, however what it does in regards to this library, is modifies how the width is applied, which is really the only effect: https://github.com/colbyfayock/next-cloudinary/blob/main/next-cloudinary/src/loaders/cloudinary-loader.ts#L44

**Comment by ColbyMay** [comment]
Hey @colbyfayock thanks for looking into this. 

That's my expectation with `fill` is the Next.js Image fill prop not actually modifying the Cloudinary URL in anyway. 

In my usage of Cloudinary + Next I've been less likely to use a set width/height and more likely to use an aspect ratio for images and image containers, using next.js `fill`. Then adding Cloudinary transformation to apply the crop and aspect ratio to the image to achieve the most responsive treatment to media. So was hoping your tool would allow for an all-encompassing solution.

I've been trying a few things to just get an aspect ratio 1/1 image. Noticed another thing in uncovering this. 

`fill={true}` with `crop` prop breaks the URL by giving a transformation that returns a height of undefined.

`<CldImage
      src={imageUrl}
      fill='true'
      crop='fill'
      alt={image.alt}
  />`
  
  **Returns**
`https://res.cloudinary.com/dg2xhiogs/image/upload/c_fill,w_750,h_undefined,g_auto/f_auto/q_auto/v1696456657/All-Pro-06_inwfwq?_a=BAVALBAO0`

The h_undefined being applied to the URL here is what I am assuming is the combination of crop + fill?

**Comment by colbyfayock** [comment]
ah okay, thanks for flagging that as well. ill add that to my test cases to resolve. i think the crop is coupled to the height (unless the crop mode doesnt support height), looks like that needs some adjustment since the height may not exist

https://github.com/colbyfayock/cloudinary-util/blob/main/packages/url-loader/src/plugins/cropping.ts#L62

**Comment by colbyfayock** [comment]
hey @ColbyMay should now be availble on latest. Here's an example usage that i believe is similar to what you were looking to do: 

https://next.cloudinary.dev/cldimage/examples#fill-parent

one thing to note is i did not add it into the `effects` array. the original intent for that was to be more artistic or transformative effects, though im not sure if that makes sense anymore with such a limited scope, as this should arguably be part of that, or really any transformation supported in a chain format

all the effects supported for instance: https://github.com/colbyfayock/cloudinary-util/blob/main/packages/url-loader/src/constants/qualifiers.ts#L96

i'll think on that more but hoping this unblocks you in the meantime!

**Comment by ColbyMay** [comment]
Cheers, @colbyfayock works exactly as expected! Nice work.

**Comment by antoinerousseau** [comment]
Hey, using v6.5.2 here, I added `aspectRatio="16:9"` on my `<CldImage>` but it doesn't add `ar_16:9` to the URL

**Comment by antoinerousseau** [comment]
@colbyfayock thanks for the detailed explanation, makes sense!
