### ISSUE TITLE
Add UploadWidget component that works out of the box with Next.js

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-cloudinary#4]
Cloudinary offers an Upload widget that works by adding a script tag to the page.

We can make the Next.js-ready by building a component around it.

Here is how we can approach this:
* https://github.com/colbyfayock/cloudinary-examples/tree/main/examples/nextjs-upload-widget-signed
* https://github.com/colbyfayock/cloudinary-examples/tree/main/examples/nextjs-upload-widget-preset

**Comment by agbanusi** [comment]
Hi @colbyfayock, I can help with this.

**Comment by colbyfayock** [comment]
hey sure, go for it! please check out the 2 examples I have there, I'd likely want to start from those unless you have any suggestions. Thanks!

**Comment by Sambhav250703** [comment]
Can I work on this issue?  @colbyfayock

**Comment by Sambhav250703** [comment]
Can I work on this issue?  @colbyfayock

**Comment by agbanusi** [comment]
> hey @agbanusi checking in - do you plan on working on this one still?

Apologies for my miscommunication, yes I am working on it and intend to make a PR for it this week, most probably thursday.

**Comment by colbyfayock** [comment]
sounds great thanks for the heads up!!

**Comment by colbyfayock** [comment]
fixed via #27
