### ISSUE TITLE
Add a testing suite to give the ability to write tests

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-cloudinary#5]
The project needs a testing solution so we can validate component logic.

Before moving forward with a pull request, please suggest solutions.

**Comment by kbravh** [comment]
I'd be happy to help out with this. [Jest](https://jestjs.io/) is a great choice for the test framework since it's so widely used. Another option is [Vitest](https://vitest.dev/), which requires some other dependencies like Vite, but it's blazing fast.

**Comment by colbyfayock** [comment]
@kbravh jest sounds great! Vite sounds interesting but i'm less familiar with that world yet, so sticking with something that can be a little simpler for now would be nice

I'll assign it over!
