### ISSUE TITLE
Implement Semantic Release

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-cloudinary#7]
Add Semantic Release to automate versioning and management

https://github.com/semantic-release/semantic-release

**Comment by Azanul** [comment]
I'd like to work on this issue

**Comment by colbyfayock** [comment]
hey @Azanul when implementing can you check out all of the configuration added here including the GitHub Action and `.releaserc`? https://github.com/colbyfayock/netlify-plugin-cloudinary

I'm open to changes as this its the first project I've used it on (it was added as a contribution with changes I had to additionally make), so interested to hear if you hvae any ideas for improvements, otherwise we can implement it the same, thanks

**Comment by Azanul** [comment]
@colbyfayock , Checkout the PR. I haven't changed much. But I think moving forward keep these two issues in our mind [semantic-release issue #2351](https://github.com/semantic-release/semantic-release/issues/2351) and [semantic-release issue #2584](https://github.com/semantic-release/semantic-release/issues/2584).

**Comment by colbyfayock** [comment]
interesting, thanks for the heads up
