### ISSUE TITLE
[Feature] Rounded Corners

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-cloudinary#73]
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

Add the `r` radius effect in an intuitive prop for rounding corners

## **Describe the solution you'd like**

In addition to generally supporting `radius`, could do `roundCorners` or `borderRadius` to adhere similar to CSS?

**Comment by roopeshsn** [comment]
Hi, @colbyfayock! I would like to work on this! I have found the documentation to implement from Cloudinary: https://cloudinary.com/documentation/effects_and_artistic_enhancements#:~:text=Transformation%20Reference.-,Rounding,-Many%20website%20designs

**Comment by colbyfayock** [comment]
sounds good @roopeshsn 

we'll want to do two things here:
- Add radius as an option to the `effects` grouping in `src/constants/qualifiers.js`
- Add a new plugin for rounded corners

For the second one, you can use the `src/plugins/remove-background.js` as an example

Along the lines of `src/plugins/round-corners.js` which would use a prop of `roundCorners` with options

**Comment by roopeshsn** [comment]
Got it @colbyfayock. Could you assign this issue to me?

**Comment by colbyfayock** [comment]
done!

**Comment by colbyfayock** [comment]
was added to Cloudinary Util via: https://github.com/colbyfayock/cloudinary-util/pull/31

this should now "just work" as the package has been updated since then, just may need an entry in docs
