### ISSUE TITLE
[Bug] Blurred placeholder's aren't showing

### ISSUE THREAD

**Issue by ThusStyles** [colbyfayock/next-cloudinary#75]
# **Bug Report**

## **Describe the bug**
The placeholder doesn't appear on the image background, this also happens on the examples page here - https://next-cloudinary.spacejelly.dev/components/cldimage/examples

Seems like from the next js docs it needs to be a base64 encoded image instead of a url

## **Is this a regression?**
Not sure

## **Steps To Reproduce the error**

1. Add a CldImage component
2. Set the placeholder="blur" option
3. Delete the src and srcset attributes on inspect to view the unloaded image
4. See there's no placeholder image showing

## **Expected behaviour**
The image should show a blurred placeholder

## **Screenshot or Video Recording**
![image](https://user-images.githubusercontent.com/2779884/205460293-7522c506-9115-46a6-8186-0733014aecb0.png)

**Comment by colbyfayock** [comment]
thanks for catching this, wonder if this was a Next.js 13 or regression before, it used to work. missed it either way. will get a fix in for this

**Comment by colbyfayock** [comment]
having a challenge figuring this one out

so given that it requires the base64 version, i ideally need to download the image URL and provide that as the result. i wouldn't want that logic to occur clientside, but then i'd have a hydration mismatch

it seems that i have a few options:
- delete the placeholder prop and it's completely unsupported
- perhaps i add an option where it's a solid color that just gets added, so it still has _something_ there instead of not supported at all, but it obviously isn't the intended solution

open to ideas, but to avoid it being broken, for now, i think im going to move forward with the color box

**Comment by theostylesffc** [comment]
Yeah maybe colour option for now, but would it be possible to have the blur uri as a prop we can pass in rather than auto setting it? Just thinking it can still be used in the new server components then and it can be down to the user to generate the base64 data

**Comment by ThusStyles** [comment]
Yeah maybe colour option for now, but would it be possible to have the blur uri as a prop we can pass in rather than auto setting it? Just thinking it can still be used in the new server components then and it can be down to the user to generate the base64 data

**Comment by ThusStyles** [comment]
I've been testing it with a next js 13 test repo and it's working fine my end with server components!

**Comment by colbyfayock** [comment]
okay, after thinking through this and reading a bit more on it, it seems like its probably not a great idea to try to wedge this in anymore without a solid way to make it work

i was reading here which provided some solutions which include loading the placeholders in places like getStaticProps which works, but doesnt relaly make sense in the context of this library

https://github.com/vercel/next.js/issues/42140

im open to the idea of adding back in a createPlaceholderUrl function as a helper in [Cloudinary Util](https://github.com/colbyfayock/cloudinary-util) if that could be valuable

in the use case, you would use that function to create the placeholder manually in getStaticProps / etc and pass that into the application

would love for a way to automate this reliably between all next versions but for now i dont really see a way. can address later
