### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by cobbvanth** [colbyfayock/next-cloudinary#77]
# **Feature Request**
Basic typings for the ClgImage component and more.

## **Describe the solution you'd like**

Begin moving the project to a Typescript-first experience. This will get harder as the project gets bigger. Happy to help with this transition!

Having prop typings for components is pretty much essential for libraries at this point, as they provide inline documentation.

**Comment by cobbvanth** [comment]
Does anyone have a full list of props and their options for the CldImage components? It will help greatly for attempting to begin this transition!

**Comment by colbyfayock** [comment]
hey @cobbvanth i dont have a single defined list

The documentation _should_ have an up to date list

But generally, each plugin file defines the props that it uses, such as `plugins/cropping.js`:
```
export const props = ['crop', 'gravity'];
```

**Comment by cobbvanth** [comment]
> hey @cobbvanth i dont have a single defined list
> 
> The documentation _should_ have an up to date list
> 
> But generally, each plugin file defines the props that it uses, such as `plugins/cropping.js`:
> 
> ```
> export const props = ['crop', 'gravity'];
> ```

Awesome, i'll start with a declaration file, and look through both your docs + the Cloudinary docs. That should get us pretty close to covering most of them.

Thanks!

**Comment by colbyfayock** [comment]
I'm a TS noob, but if there's a way to use the props as defined in the plugins files to populate the definitions, i would think that'd be ideal. or ive seen where you can use comments to define those? thinking that it would be as close to the source as possible, just making it easier to look around, not sure

we can expand the props arrays to do like { name: 'crop', type: 'string' } if that helps

**Comment by cobbvanth** [comment]
> I'm a TS noob, but if there's a way to use the props as defined in the plugins files to populate the definitions, i would think that'd be ideal. or ive seen where you can use comments to define those? thinking that it would be as close to the source as possible, just making it easier to look around, not sure
> 
> we can expand the props arrays to do like { name: 'crop', type: 'string' } if that helps

There are basically two ways we can do it. 

- We can either incrementally re write the entire project in TS, which will automatically generate the typings for everything we need (this one should be done ASAP, as the longer we wait, the harder it will be). It's not as hard as you might think!
- We can write a .d.ts (TS declaration file), which is just a small file that sits in the @types folder and will provide external type defs to the JS code. This is what Express and Node itself uses, as they were written before TS was very popular. 
![image](https://user-images.githubusercontent.com/80018012/207080919-a571223f-2544-4785-9297-891b2067df02.png)


This then makes it extremely easy for people to download the typings for the project, without needing a full re-write immediately. (You just have to type `npm i @types/next-cloudinary`)

I've already written a good chunk of the declaration file, although it is missing a few props/specific defs, but it's looking very usable! I'll drop a pull request ASAP.

**Comment by colbyfayock** [comment]
got it okay, thanks. as far as rewriting, what would rewriting actually look like? can you give me an example of a function or something?

**Comment by cobbvanth** [comment]
The great things about Typescript is that it's fully incremental, we can start by adding typings to only a few of the functions, and expand out from there.

An example would be:

`

type ImageProps = {

src: string;
alt: string;
width: number;
height: number;
etc...
}

export const CloudinaryImageComponent = (props : ImageProps)
{

 return <img.../>
}
`

It's that simple for most things!

**Comment by colbyfayock** [comment]
awesome thanks. looking forward to seeing what you come up with
