### ISSUE TITLE
[Feature] Screen, Multiply, and Other Layer Effects

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-cloudinary#85]
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

```
multiply
screen
```

**Comment by roopeshsn** [comment]
Hi @colbyfayock! Could you elaborate on this?

**Comment by colbyfayock** [comment]
hey @roopeshsn i'm already working on this one, sorry for the confusion
