### ISSUE TITLE
Support for metadata fetching

### ISSUE THREAD

**Issue by Liloa** [colbyfayock/next-cloudinary#95]
Hi does this library support pulling metadata associated with a cloudinary media?

**Comment by colbyfayock** [comment]
hey @Liloa it doesn't currently support that functionality. what are you trying to accomplish?

one way to do this is to use the Cloudinary Node.js SDK inside of data fetching methods or inside of a Next.js Serverless Function

**Comment by Liloa** [comment]
Was working with a friend to use cloudinary to store images for a portfolio website and query cloudinary for the images and associated metadata to display on the site, not an issue if its not a supported feature though.  Thank you

**Comment by colbyfayock** [comment]
Yeah theoretically I could make something that could be used as a helper hut i recommend using the node SDK in a serverless function for that!
